<template>
  <div class="loadingio-spinner-spinner-dv9npdc2jfp">
    <div class="ldio-a3k33aev40w">
      <div></div>
      <div></div>
    </div>
  </div>
</template>
<script>
export default {
  name: "FailureIcon",
};
</script>


<style scoped>
@keyframes ldio-a3k33aev40w {
  0% {
  }
  100% {
  }
}
.ldio-a3k33aev40w div {
  left: 20px;
  top: 48px;
  position: absolute;
  animation: ldio-a3k33aev40w linear 1s infinite;
  background: #6a6a6a;
  width: 80px;
  height: 24px;
  border-radius: 0px / 0px;
  transform-origin: center;
}
.ldio-a3k33aev40w div:nth-child(1) {
  transform: rotate(-45deg);
  animation-delay: -0.9166666666666666s;
  background: #b30303;
}
.ldio-a3k33aev40w div:nth-child(2) {
  transform: rotate(45deg);
  animation-delay: -0.8333333333333334s;
  background: #b30303;
}
.loadingio-spinner-spinner-dv9npdc2jfp {
  width: 120px;
  height: 120px;
  display: inline-block;
  overflow: hidden;
}
.ldio-a3k33aev40w {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-a3k33aev40w div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>