<template>
  <div class="loadingio-spinner-spinner-dv9npdc2jfp">
    <div class="ldio-a3k33aev40w">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>
<script>
export default {
  name: "LoadingIcon",
};
</script>


<style scoped>
@keyframes ldio-a3k33aev40w {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-a3k33aev40w div {
  left: 47%;
  top: 10%;
  position: absolute;
  animation: ldio-a3k33aev40w linear 1s infinite;
  background: #6a6a6a;
  width: 8px;
  height: 24px;
  border-radius: 0px / 0px;
  transform-origin: 4px 52px;
}
.ldio-a3k33aev40w div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9166666666666666s;
  background: #6a6a6a;
}
.ldio-a3k33aev40w div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.8333333333333334s;
  background: #6a6a6a;
}
.ldio-a3k33aev40w div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.75s;
  background: #6a6a6a;
}
.ldio-a3k33aev40w div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.6666666666666666s;
  background: #6a6a6a;
}
.ldio-a3k33aev40w div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.5833333333333334s;
  background: #6a6a6a;
}
.ldio-a3k33aev40w div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.5s;
  background: #6a6a6a;
}
.ldio-a3k33aev40w div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.4166666666666667s;
  background: #6a6a6a;
}
.ldio-a3k33aev40w div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3333333333333333s;
  background: #6a6a6a;
}
.ldio-a3k33aev40w div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.25s;
  background: #6a6a6a;
}
.ldio-a3k33aev40w div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.16666666666666666s;
  background: #6a6a6a;
}
.ldio-a3k33aev40w div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.08333333333333333s;
  background: #6a6a6a;
}
.ldio-a3k33aev40w div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #6a6a6a;
}
.loadingio-spinner-spinner-dv9npdc2jfp {
  width: 120px;
  height: 120px;
  display: inline-block;
  overflow: hidden;
}
.ldio-a3k33aev40w {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-a3k33aev40w div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>